import { Resources } from './resource.model';

export const SAVED_RESOURCES: Resources[] = [
  {
    'id' : 1,
    'type': 'BOOK',
    'name': 'Packt Pub',
    'url': 'https://www.packtpub.com/',
    'comments' : 'Free Book-A-Day',
  },
  {
    'id' : 2,
    'type': 'BOOK',
    'name': 'GitHub',
    'url': 'https://github.com/EbookFoundation/free-programming-books',
    'comments' : '95% of the Links still work, just prep for disapointment',
  },
  {
    'id' : 3,
    'type': 'BOOK',
    'name': 'Reddit',
    'url': 'https://www.reddit.com/r/learnprogramming/',
    'comments' : 'Community of Resources',
  },
  {
    'id' : 4,
    'type': 'BOOK',
    'name': 'HumbleBundle',
    'url': 'https://www.humblebundle.com/',
    'comments' : 'Occasional Book Bundles',
  },
  {
    'id' : 5,
    'type': 'BOOK',
    'name': 'Amazon',
    'url': 'https://www.amazon.com/',
    'comments' : 'Purchase Programming Books',
  },
  {
    'id' : 6,
    'type': 'VIDEO',
    'name': 'UNT Lynda',
    'url': 'https://www.it.unt.edu/lynda',
    'comments' : 'Use UNT Login Credentials',
  },
  {
    'id' : 7,
    'type': 'VIDEO',
    'name': 'Lynda',
    'url': 'https://www.Lynda.com',
    'comments' : 'Classes can be a bit dry, but otherwise enlightening',
  },
  {
    'id' : 8,
    'type': 'VIDEO',
    'name': 'Udemy',
    'url': 'https://www.Udemy.com',
    'comments' : 'Wait for their frequent sales',
  },
  {
    'id' : 9,
    'type': 'VIDEO',
    'name': 'Coursera',
    'url': 'https://www.Coursera.com',
    'comments' : 'Most of the Instruction if in a Class-type Format',
  },
  {
    'id' : 10,
    'type': 'VIDEO',
    'name': 'PluralSight',
    'url': 'https://www.pluralsight.com/',
    'comments' : 'Expensive, but great reviews',
  },
  {
    'id' : 11,
    'type': 'CAMP',
    'name': 'FreeCodeCamp',
    'url': 'https://www.freecodecamp.org/',
    'comments' : '300 Hours so be prepared',
  },
  {
    'id' : 12,
    'type': 'CAMP',
    'name': 'CodeAcademy',
    'url': 'https://www.codecademy.com/',
    'comments' : 'Solid Introductory Material, great if your a bit scared',
  },
  {
    'id' : 13,
    'type': 'CLUB',
    'name': 'UNT IEEE: Computer Society',
    'url': 'UNTIEEECS.slack.com',
    'comments' : 'Use Channel: #resources',
  },
  {
    'id' : 14,
    'type': 'CLUB',
    'name': 'UNT Cyber Security',
    'url': 'UNTCCSI.slack.com',
    'comments' : 'Use Channel: #resources',
  },
];
